[meta]
authors=["bharath-swamy"]
title="Demonstrate some common AI function usecases"
description="""\
    Learn how to connect to use \
    pre configured AI Functions.
    """
icon="browser"
difficulty="beginner"
tags=["advanced", "notebooks", "python"]
lesson_areas=[]
destinations=["spaces"]
minimum_tier="standard"
