[meta]
authors=["singlestore"]
title="Publish your first SingleStore Cloud function"
description="""\
    Leran how to connect to SingleStoreDB and perform basic 
    CRUD operations and finally deploy these functions as callable API endpoints.
    """
icon="browser"
difficulty="beginner"
tags=["starter", "notebooks", "python"]
lesson_areas=[]
destinations=["spaces"]
minimum_tier="free-shared"
