[meta]
authors=["bharath-swamy"]
title="Demonstrate ML function Classify"
description="""\
    Learn how to train an ML Classify \
    model and run it to predict the class of an input row.
    """
icon="browser"
difficulty="beginner"
tags=["advanced", "notebooks", "python"]
lesson_areas=["AI"]
destinations=["spaces"]
minimum_tier="standard"
