[meta]
authors=["bharath-swamy"]
title="Python UDF to process images"
description="""\
    Learn how to integrate with Multimodal LLMs \
    and run it from a python UDF.
    """
icon="browser"
difficulty="beginner"
tags=["advanced", "notebooks", "python"]
lesson_areas=["AI"]
destinations=["spaces"]
minimum_tier="standard"
